export const DISPLAY_ALERT = "SHOW_ALERT"
export const REMOVE_ALERT = "HIDE_ALERT"

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_Error = "LOGIN_USER_ERROR"

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_FORM = 'CLEAR_FORM'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_FAIL = 'EDIT_JOB_FAIL'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

export const GET_STATS_BEGIN = 'GET_STATS_BEGIN'
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'